enemy_health = room; //health is equal to the current room number
damage = 1; //the enemies only do 1 damage
grav = 0.5;
hsp = 4;
vsp = 0;
jumpspeed = 9;
movespeed = 4;
frame = 0;
direc = "left";
dead = false;
